#!/bin/bash

commit-or-branch = action-get commit-or-branch

if [[ commit-or-branch == "" ]]; then
  echo "Cannot update to a commit without a commit or branch"
  exit 0
fi

cd $(config-get app-path)
git fetch origin master
git checkout $(action-get commit-or-branch)
